[package]
name = "lottery-tickets-examples"
version = "0.0.0"
authors = [ "Typas Liao <typascake@gmail.com>" ]
edition = "2024"

[[example]]
name = "one_prize_per_user"
path = "src/one_prize_per_user.rs"

[[example]]
name = "unlimited_prizes_per_user"
path = "src/unlimited_prizes_per_user.rs"

[dependencies.lottery-tickets]
path = "../"
