[package]
name = "benches"
version = "0.0.0"
authors = [ "Typas Liao <typascake@gmail.com>" ]
edition = "2024"
publish = false

[dev-dependencies]
lottery-tickets = { path = ".." }
criterion = "0.5"
rand = "0.9"
rand_xoshiro = "0.7"
rand_chacha = "0.9"
gxhash = "3.5"
jemalloc-ctl = "0.5"

[dev-dependencies.jemallocator]
version = "0.5"
features = ["stats", "profiling", "unprefixed_malloc_on_supported_platforms"]

[profile.bench]
debug = true

[features]
default = ["array", "tree"]
array = []
tree = []

[[bench]]
name = "single-prize"
harness = false

[[bench]]
name = "multiple-prize"
harness = false
